export const FETCH_CHANNELS_LIST_SUCCESS = "FETCH_CHANNELS_LIST_SUCCESS";
export const UPDATE_ACTIVE_CHANNEL_SUCCESS = "UPDATE_ACTIVE_CHANNEL_SUCCESS";
export const FETCH_CHANNELS_LIST_FAILURE = "FETCH_CHANNELS_LIST_FAILURE";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const POST_NEW_MESSAGE = "POST_NEW_MESSAGE";
export const HANDLE_EDIT_PANEL = "HANDLE_EDIT_PANEL";
